landing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from landing import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^landing123/$', views.landing, name='landing'),
]

orders/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from landing import views

urlpatterns = [
    # url(r'^landing123/', views.landing, name='landing'),
]

products/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from products import views

urlpatterns = [
    # url(r'^landing123/', views.landing, name='landing'),
    url(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
]

python_django_net_magazine/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^', include('products.urls')),
    url(r'^', include('orders.urls')),
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/models.py
from django.db import models


class Subscriber(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=128)

    def __str__(self):
        return "Пользователь %s %s" % (self.name, self.email,)

    class Meta:
        verbose_name = 'MySubscriber'
        verbose_name_plural = 'A lot of Subscribers'

orders/models.py
from django.db import models
from products.models import Product
from django.db.models.signals import post_save


class Status(models.Model):
    name = models.CharField(max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "Статус %s" % self.name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказа'


class Order(models.Model):
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)#total price for all products in order
    customer_name = models.CharField(max_length=64, blank=True, null=True, default=None)
    customer_email = models.EmailField(blank=True, null=True, default=None)
    customer_phone = models.CharField(max_length=48, blank=True, null=True, default=None)
    customer_address = models.CharField(max_length=128, blank=True, null=True, default=None)
    comments = models.TextField(blank=True, null=True, default=None)
    status = models.ForeignKey(Status)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "Заказ %s %s" % (self.id, self.status.name)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def save(self, *args, **kwargs):

        super(Order, self).save(*args, **kwargs)


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, blank=True, null=True, default=None)
    product = models.ForeignKey(Product, blank=True, null=True, default=None)
    nmb = models.IntegerField(default=1)
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)#price*nmb
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.product.name

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'


    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        self.total_price = self.nmb * price_per_item

        super(ProductInOrder, self).save(*args, **kwargs)



def product_in_order_post_save(sender, instance, created, **kwargs):
    order = instance.order
    all_products_in_order = ProductInOrder.objects.filter(order=order, is_active=True)

    order_total_price = 0
    for item in all_products_in_order:
        order_total_price += item.total_price

    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)


post_save.connect(product_in_order_post_save, sender=ProductInOrder)

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'


class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None)
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s, %s" % (self.price, self.name)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

landing/forms.py
from django import forms
from .models import *


class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        exclude = [""]

orders/forms.py
from django import forms
from .models import *


# class SubscriberForm(forms.ModelForm):
#
#     class Meta:
#         model = Subscriber
#         exclude = [""]
#

products/forms.py
from django import forms
from .models import *


# class SubscriberForm(forms.ModelForm):
#
#     class Meta:
#         model = Subscriber
#         exclude = [""]

landing/views.py
from django.shortcuts import render
from .forms import SubscriberForm
from products.models import *


def landing(request):
    name = "CodingMedved"
    current_day = "03.01.2017"
    form = SubscriberForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        print (request.POST)
        print (form.cleaned_data)
        data  = form.cleaned_data
        print (data["name"])

        new_form = form.save()

    return render(request, 'landing/landing.html', locals())


def home(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_phones = products_images.filter(product__category__id=1)
    products_images_laptops = products_images.filter(product__category__id=2)
    return render(request, 'landing/home.html', locals())

products/views.py
from django.shortcuts import render
from products.models import *


def product(request, product_id):
    product = Product.objects.get(id=product_id)
    return render(request, 'products/product.html', locals())

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400" rel="stylesheet">

    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>
<body>

    <div class="wrapper">
        <div class="wrapper-content">
            {% include 'navbar.html' %}

            {% block content %}
            {% endblock content %}
        </div>

    </div>

     {% include 'footer.html' %}


    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container">
        <div class="text">
            <h3>FOOTER</h3>
        </div>
    </div>
</footer>

templates/landing/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="section-top">
        <img src="{% static 'img/slider0.jpg' %}" class="img-responsive">
    </div>
    <div class="section section1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Новые поступления
                    </h1>
                </div>
                {% for product_image in products_images %}
                    {% include 'landing/product_item.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="section section-delivery">
        <div>
            <h3>Free shipping</h3>
        </div>
    </div>
    <div class="section section2 phones-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Телефоны
                    </h1>
                </div>
                {% for product_image in products_images_phones %}
                    {% include 'landing/product_item.html' %}
                {% endfor %}

            </div>
        </div>
    </div>
    <div class="section section3 laptops-container">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Ноутбуки
                    </h1>
                </div>
                {% for product_image in products_images_laptops %}
                    {% include 'landing/product_item.html' %}
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

templates/landing/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400" rel="stylesheet">

    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'css/landing.css' %}">


</head>
<body>

    <div class="general-container">
        <div class="container top-container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1 class="title">Наш магазин скоро откроется!<br>
                    Оставляйте Ваш имейл в форме ниже</h1>
                    <div>
                        <form action="" method="post" class="form-inline text-center">{% csrf_token %}
                         <div class="form-group">
                             <label>Ваш имейл: </label>
                             <input name="{{ form.email.name }}" class="form-control">
                         </div>
                         <div class="form-group">
                             <label>Ваше имя: </label>
                             <input name="{{ form.name.name }}" class="form-control">
                         </div>
                         <button type="submit" class="btn btn-primary btn-orange">Отправить</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


</body>
</html>

templates/landing/product_item.html
<div class="col-lg-3">
    <div class="product-item">
        <div>
            <a href="{% url 'product' product_image.product.id %}">
                <img src="{{ product_image.image.url }}" class="img-responsive">
            </a>
        </div>

        {% if product_image.product.discount %}
            <div class="discount-container">
                <span>{{ product_image.product.discount }}%</span>
            </div>
        {% endif %}

        <h4>{{ product_image.product.name }}</h4>
        <p>
            {{ product_image.product.description|truncatechars_html:70 }}
        </p>
        <div>
            {{ product_image.product.price }} UAH
        </div>
        <div class="add-to-card-btn">
            <button class="btn btn-success">
                Добавить в корзину
            </button>
        </div>
    </div>
</div>

templates/navbar.html
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Домой</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

templates/products/product.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item">
                        <img src="{{ image_item.image.url }}" class="img-responsive">
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Price: {{ product.price }}
                    </p>
                </div>
                <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                                Описание
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">
                                Доставка
                            </a>
                        </li>
                        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
                        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content product-description-tabs">
                        <div role="tabpanel" class="tab-pane active" id="description">
                            {{ product.description }}
                        </div>
                        <div role="tabpanel" class="tab-pane" id="delivery">
                            <h3>Как мы делаем доставку</h3>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="messages">...</div>
                        <div role="tabpanel" class="tab-pane" id="settings">...</div>
                      </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}